spring:

  application:
    name: checkout

  kafka:
    consumer:
      group-id: checkout-${random.uuid}
      auto-offset-reset: earliest
    bootstrap-servers: broker:29092

server:
  port: 8082

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true

opentracing:
  jaeger:
    http-sender:
      url: http://jaegertracing:6831/api/traces

