spring:

  application:
    name: checkout

  kafka:
    consumer:
      group-id: checkout-${random.uuid}
      auto-offset-reset: earliest
    bootstrap-servers: 10.108.199.157:9092

server:
  port: 8082

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true

