spring:

  application:
    name: catalogue

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: catalogue-${random.uuid}
      auto-offset-reset: earliest

    cloud:
      consul:
        discovery:
          # see https://github.com/spring-cloud/spring-cloud-consul/issues/365
          health-check-path: /info


server:
  port: 8082

management:
  endpoints:
    health:
      show-details: true

  web:
    exposure:
      include: "*"

