spring:

  application:
    name: catalogue

  kafka:
    consumer:
      group-id: catalogue-${random.uuid}
      auto-offset-reset: earliest

server:
  port: 8082

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true

